[package]
name = "automated_pentesting"
version = "0.1.0"
edition = "2021"

# Descripción del proyecto
description = "Un proyecto para escanear puertos y buscar vulnerabilidades utilizando Nmap y CVE."

# Dependencias del proyecto
[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv= "0.15"
# Para permitir trabajar con el formato de salida de Nmap
[dependencies.regex]
version = "1.5"
